/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stddef.h>

#include "stm32f407xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	I2C_Config_t config = {
			I2C_SPEED_SM,
			62,
			I2C_ACK_EN,
			I2C_FM_DUTY_2
	};

	I2C_Handle_t p_i2c_handle = {
			I2C1,
			config,
			NULL,
			NULL,
			0,
			0,
			0,
			21,
			0,
			0
	};

    /* Loop forever */
	I2C_Init(&p_i2c_handle);

	for(;;);
}
